config/routes.rb
SsqlWebExtractionApi::Application.routes.draw do
  scope "(:locale)", locale: /en|fr|ja/ do
    devise_for :users
    resources :centroids, only: :create, defaults: {format: 'json'}
    get 'websites/extraction', to: 'websites#extraction'
    get 'about', to: 'pages#about'
    get 'contact', to: 'pages#contact'
    get 'documentation', to: 'pages#documentation'
    resources :websites, only: [:new, :index, :destroy, :show] do 
      resources :labels do 
        get 'container_items', to: 'items#container_index'
        resources :items, only: :index
      end
    end
    resources :items, only: :create
    match '/*path' => 'application#cors_preflight_check', :via => :options
  end
  get '/current_user', to: 'feedbacks#my_user'
  root 'pages#home'
  get '/:locale' => 'pages#home', constraints: {locale: /en|fr|ja/}
  get '/auth/:provider/callback', to: 'sessions#create'  
end

app/models/website.rb
class Website < ActiveRecord::Base
  has_many :extractions, dependent: :destroy
  has_many :labels, through: :extractions
  validates_uniqueness_of :url
  validates_presence_of :url
  has_many :users, through: :extractions

  def self.parse html_string
    html = html_string.sub(/^<!DOCTYPE html(.*)$/, '<!DOCTYPE html>')
    html_doc = Nokogiri::HTML html
    html_doc.at_css("base").try(:remove)
    body = html_doc.xpath "/html/body"
    head = html_doc.xpath "/html/head"
    return head, body
  end

  def self.get_html_from_node_script url, weights=nil
    bash_code = "cd #{ENV['WEB_EXTRACTION_DIR']}; node phantom.js \"#{url}\""
    bash_code += " \"#{weights.to_json}\"" if weights
    html = `#{bash_code}`
  end

  def self.update_items
    `cd #{ENV['WEB_EXTRACTION_DIR']}; node result.js`
  end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController

  PROPERTIES_ARRAY = [:color, :background_color, :width, :height, :text_decoration, :font_style, :left_alignment, :top_alignment, :z_index, :padding_l_r, :padding_t_b, :border_horizontal_width, :border_vertical_width]

  before_filter :authenticate_user!, only: [:new, :extraction]

  def show
    @website = Website.where(id: params[:id])
    respond_to do |format|
      format.json {render json: @website.to_json(include: :labels)}
      format.xml {render xml: @website.to_xml(include: :labels)}
      format.csv {render text: @website.to_csv}
      format.xls {send_data @website.to_csv(col_sep: "\t")}
      format.html {authenticate_user!; render layout: 'dashboard'}
    end
  end

  def get_from_label
    @centroid = Centroid.where(params.slice(:website_id, :label)).first
    @items = @centroid.items
    render json: @items
  end

  def index 
    @websites = Website.includes(:labels => :centroids).order("websites.id DESC")
    respond_to do |format|
      format.json {render json: @websites.to_json(include: {labels: {include: :centroids}} ) }
      format.xml {render xml: @websites.to_xml(include: {labels: {include: :centroids}} ) }
      format.csv {render text: @websites.to_csv}
      format.xls {send_data @websites.to_csv(col_sep: "\t")}
      format.html{authenticate_user!; render layout: 'dashboard'}
    end
  end

  def new
    render layout: 'dashboard'
  end

  def extraction
    @url = params[:url]
    @url.strip!
    if !@url.start_with? "http"
      @url = "http://#{@url}"
    end
    @weights = params[:weights]
    temp = []
    PROPERTIES_ARRAY.each do |property|
      temp << @weights[property]
    end
    @weights = temp
    @weights.map! do |weight|
      if weight.blank?
        1
      else
        weight.to_f
      end
    end
    @html = Website.get_html_from_node_script(@url, @weights)
    # p @html
    temp = {}
    PROPERTIES_ARRAY.each_with_index do |property, index|
      temp[property] = @weights[index]
    end
    @weights = temp
    @head, @body = Website.parse(@html).map(&:to_html)
    render layout: false
  end

  def destroy
    Website.find(params[:id]).destroy
    redirect_to websites_path
  end
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/websites/extraction.html.haml
!!!
%html
  %head
    =raw(@head)
    = stylesheet_link_tag "extraction"
    =javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.2/underscore-min.js", "extraction/extraction"
    :javascript
      underscore = _;
      jq = $
    %meta{name: :url, content: @url}
  %body
    .extraction-navbar
      .navbar-header.extraction-left
        =link_to "Web extraction engine", root_path, confirm: "Are you sure you want to leave this page ?", class: :root_link
      .extraction-right
        %span Choose the level of the extraction
        =select_tag :level, options_for_select([1,2,3,4,5], 2)
        %button.extraction-button{'data-container' => "body", 'data-toggle' => "popover", 'data-placement' => "bottom"} Label
        %button.extraction-reset-button Reset
        %button.extraction-submit-button Save
        =image_tag 'loader.gif', class: [:loader, :hidden]
        =image_tag 'config.png',size: "32x32", class: :config
      .extraction-center
        =image_tag "cross.png", size: "32x32", class: :cross
        =image_tag "plus.png", size: "32x32", class: [:selected, :plus]
        / # =image_tag "minus.png", size: "32x32", class: :minus
    #config-panel{style: "display:none"}
      List of labels :
      %br
    #original_page
      = raw(@body)

:javascript
  weights = #{@weights.to_json};

app/views/websites/index.html.haml
%h1.page-header= t('websites.index.header')
%table.table
  %thead
    %tr
      %th #
      %th Url
      %th= t('label.many')
      %th
      %th
      %th
      %th Actions
  %tbody
    - @websites.each_with_index do |website, index|
      %tr
        %td{rowspan: website.labels.size}= website.id
        %td{rowspan: website.labels.size}= website.url
        - if website.labels.first
          %td= website.labels.first.value
          %td= link_to "Show", website_label_items_path(website, website.labels.first)
          %td= link_to "Edit label", edit_website_label_path(website, website.labels.first)
          %td= link_to "Delete label", website_label_path(website, website.labels.first), method: :delete, data: {confirm: "Are you sure ?"}
        %td= link_to "Delete website", website_path(website), method: :delete, data: {confirm: "Are you sure ?"}
      - website.labels.each_with_index do |label, index|
        - if index != 0
          %tr
            %td= label.value
            %td= link_to "Show", website_label_items_path(website,label)
            %td= link_to "Edit label", edit_website_label_path(website,label)
            %td= link_to "Delete label", website_label_path(website, label), method: :delete, data: {confirm: "Are you sure ?"}

app/views/websites/new.html.haml
%h1.page-header=t('websites.new.header')
.col-md-8.col-md-offset-2
  = form_tag websites_extraction_path, method: :get, id: :new_website_form do
    .form-group
      = label_tag :url, t('websites.new.url')
      = text_field_tag :url, "", class: 'form-control', placeholder: t('websites.new.url_ph')
    = button_tag t('websites.new.submit'), class: ['btn', 'btn-default']
    = image_tag 'loader.gif', class: ['loader', 'hidden']
    %hr
    .form_group
      =label_tag :weights, t('websites.new.weights_notice')
      .row
        .col-md-2=label_tag 'weights[color]', t('websites.new.weights.color')
        .col-md-2=number_field_tag 'weights[color]', "", :step => 0.01, class: 'form-control', placeholder: '1.00'
        .col-md-2=label_tag 'weights[background_color]', t('websites.new.weights.bg_color')
        .col-md-2=number_field_tag 'weights[background_color]', "", :step => 0.01, class: 'form-control', placeholder: '1.00'
        .col-md-2=label_tag 'weights[width]', t('websites.new.weights.width')
        .col-md-2=number_field_tag 'weights[width]', "", :step => 0.01, class: 'form-control', placeholder: '1.00'
      %br
      .row  
        .col-md-2=label_tag 'weights[height]', t('websites.new.weights.height')
        .col-md-2=number_field_tag 'weights[height]', "", :step => 0.01, class: 'form-control', placeholder: '1.00'
        .col-md-2=label_tag 'weights[text_decoration]', t('websites.new.weights.text_decoration')
        .col-md-2=number_field_tag 'weights[text_decoration]', "", :step => 0.01, class: 'form-control', placeholder: '1.00'
        .col-md-2=label_tag 'weights[font_style]', t('websites.new.weights.font_style')
        .col-md-2=number_field_tag 'weights[font_style]', "", :step => 0.01, class: 'form-control', placeholder: '1.00'
      %br
      .row
        .col-md-2=label_tag 'weights[left_alignment]', t('websites.new.weights.left_alignment')
        .col-md-2=number_field_tag 'weights[left_alignment]', "", :step => 0.01, class: 'form-control', placeholder: '1.00'
        .col-md-2=label_tag 'weights[top_alignment]', t('websites.new.weights.top_alignment')
        .col-md-2=number_field_tag 'weights[top_alignment]', "", :step => 0.01, class: 'form-control', placeholder: '1.00'
        .col-md-2=label_tag 'weights[z_index]', t('websites.new.weights.z_index')
        .col-md-2=number_field_tag 'weights[z_index]', "", :step => 0.01, class: 'form-control', placeholder: '1.00'
      %br
      .row
        .col-md-2=label_tag 'weights[padding_l_r]', t('websites.new.weights.padding_l_r')
        .col-md-2=number_field_tag 'weights[padding_l_r]', "", :step => 0.01, class: 'form-control', placeholder: '1.00'
        .col-md-2=label_tag 'weights[padding_t_b]', t('websites.new.weights.padding_t_b')
        .col-md-2=number_field_tag 'weights[padding_t_b]', "", :step => 0.01, class: 'form-control', placeholder: '1.00'
        .col-md-2=label_tag 'weights[border_horizontal_width]', t('websites.new.weights.border_horizontal_width')
        .col-md-2=number_field_tag 'weights[border_horizontal_width]', "", :step => 0.01, class: 'form-control', placeholder: '1.00'
      %br
      .row
        .col-md-2=label_tag 'weights[border_vertical_width]', t('websites.new.weights.border_vertical_width')
        .col-md-2=number_field_tag 'weights[border_vertical_width]', "", :step => 0.01, class: 'form-control', placeholder: '1.00'