config/routes.rb
SsqlWebExtractionApi::Application.routes.draw do
  scope "(:locale)", locale: /en|fr|ja/ do
    devise_for :users
    resources :centroids, only: :create, defaults: {format: 'json'}
    get 'websites/extraction', to: 'websites#extraction'
    get 'about', to: 'pages#about'
    get 'contact', to: 'pages#contact'
    get 'documentation', to: 'pages#documentation'
    resources :websites, only: [:new, :index, :destroy, :show] do 
      resources :labels do 
        get 'container_items', to: 'items#container_index'
        resources :items, only: :index
      end
    end
    resources :items, only: :create
    match '/*path' => 'application#cors_preflight_check', :via => :options
  end
  get '/current_user', to: 'feedbacks#my_user'
  root 'pages#home'
  get '/:locale' => 'pages#home', constraints: {locale: /en|fr|ja/}
  get '/auth/:provider/callback', to: 'sessions#create'  
end

app/models/item.rb
require 'csv'
class Item < ActiveRecord::Base
  belongs_to :label
  has_one :extraction, through: :label
  has_one :website, through: :extraction
  has_many :associated_labels, through: :extraction, source: :labels
  validates :value, uniqueness: {scope: :label_id}, presence: true
  before_validation :format_item
  belongs_to :parent, class_name: "Item"
  has_many :children, class_name: "Item", foreign_key: :parent_id
  belongs_to :centroid, dependent: :destroy

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |item|
        csv << item.attributes.values_at(*column_names)
      end
    end
  end

  def find_parent
    possible_parents = self.associated_labels.containers.includes(items: :centroid).map(&:items).flatten.map(&:centroid)
    container = self.centroid.try :find_container, possible_parents
    return unless container
    parent = container.items.where(label_id: self.associated_labels.containers.pluck(:id)).first
    parent if parent && self != parent && self.label != parent.label && parent.label.container
  end

  def self.generate_links
    Item.all.each do |item|
      item.parent = item.find_parent
      item.save
    end
  end

  private
  def format_item
    self.value = self.value.strip.squeeze(" ").squeeze("\n")
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @website = Website.where(id: params[:website_id]).first
    @label = Label.includes({items: :parent}, :extraction).where(extractions: {website_id: params[:website_id]}, value: params[:label_id]).first
    redirect_to websites_path and return unless @label
    @items = @label.items
    respond_to do |format|
      format.json {render json: @items}
      format.xml {render xml: @items}
      format.csv {render text: @items.to_csv}
      format.xls {send_data @items.to_csv(col_sep: "\t")}
      format.html {authenticate_user! ; render layout: 'dashboard'}
      format.txt { render text: @items.map{|item| item.value + " | " + item.link}.join("\n")}
    end
  end

  def container_index
    @website = Website.where(id: params[:website_id]).first
    @label = Label.includes({items: {children: :label}}, :extraction).where(extractions: {website_id: params[:website_id]}, value: params[:label_id]).first
    redirect_to websites_path and return unless @label && @label.container
    
    @result = []

    # Le nom des différents labels disponibles, le premier nom est value
    @label.items.map do |item|
      children = item.children
      hash = {}
      children.each do |child|
        hash[child.label.value] = child.value
      end
      hash["value"] = item.value
      @result << hash
    end
    respond_to do |format|
      format.json {render json: @result}
      format.xml {render xml: @result.to_xml}
      format.html {authenticate_user! ; render layout: 'dashboard'}
    end
  end

  def create
    @items = params[:items]
    new_items = @items.map do |item|
      image = false
      if item[:image]
        image = true
      end
      centroid = item.delete :centroid
      centroid = Centroid.create_from_array centroid
      item.merge({label_id: params[:label_id], centroid_id: centroid.id})
    end
    Item.create new_items
    render nothing: true
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.haml
%h2.page-header 
  List of extracted items for the label 
  %span.text-primary= @label.value
  of the website
  %span.text-success= @website.url
.links
  .btn-group
    =link_to "Json format", {format: :json}, class: [:btn, 'btn-default']
    =link_to "Excel format", {format: :xls}, class: [:btn, 'btn-default']
    =link_to "Csv format", {format: :csv}, class: [:btn, 'btn-default']
    =link_to "Text format", {format: :txt}, class: [:btn, 'btn-default']
    =link_to "Xml format", {format: :xml}, class: [:btn, 'btn-default']
    - if @label.container
      =link_to "Container json", website_label_container_items_path(@website, @label, {format: :json}), class: [:btn, 'btn-default']
      =link_to "Container xml", website_label_container_items_path(@website, @label, {format: :xml}), class: [:btn, 'btn-default']
%table.table.table-hover
  %thead
    %tr
      %th #
      %th value
      %th href / src
      %th Parent
  %tbody
    - @items.each_with_index do |item, index|
      %tr
        %td= item.id
        %td= item.value
        %td= item.link
        %td
          - if item.parent
            = item.parent.value
            from label
            = link_to item.parent.label.value, website_label_items_path(@website, item.parent.label)