config/routes.rb
SsqlWebExtractionApi::Application.routes.draw do
  scope "(:locale)", locale: /en|fr|ja/ do
    devise_for :users
    resources :centroids, only: :create, defaults: {format: 'json'}
    get 'websites/extraction', to: 'websites#extraction'
    get 'about', to: 'pages#about'
    get 'contact', to: 'pages#contact'
    get 'documentation', to: 'pages#documentation'
    resources :websites, only: [:new, :index, :destroy, :show] do 
      resources :labels do 
        get 'container_items', to: 'items#container_index'
        resources :items, only: :index
      end
    end
    resources :items, only: :create
    match '/*path' => 'application#cors_preflight_check', :via => :options
  end
  get '/current_user', to: 'feedbacks#my_user'
  root 'pages#home'
  get '/:locale' => 'pages#home', constraints: {locale: /en|fr|ja/}
  get '/auth/:provider/callback', to: 'sessions#create'  
end

app/views/layouts/application.html.haml
!!!
%html
  %head>
    %title Web extraction engine
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag "pages", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = yield :head
    = csrf_meta_tags
  %body
    - if flash[:notice]||flash[:alert]
      .notice=flash[:notice]||flash[:alert]
    .navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container
        .navbar-header
          %a.navbar-brand{href: root_path} Web extraction engine
        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              %a{href: root_path}= t('layout.home')
            %li
              %a{href: about_path}= t('layout.about')
            %li
              %a{href: contact_path}= t('layout.contact')
            - if user_signed_in?
              %li
                %a{href: new_website_path}= t('layout.dashboard')
            %li.dropdown
              %a.dropdown-toggle{href: "#", 'data-toggle' => "dropdown"}
                Language
                %b.caret
              %ul.dropdown-menu
                %li
                  =link_to "English", locale: :en
                %li
                  =link_to "日本語", locale: :ja
                %li
                  =link_to "Français", locale: :fr

          - if user_signed_in?
            .navbar-right.navbar-form= link_to(t('layout.logout'), destroy_user_session_path, :method => :delete, class: ['btn', 'btn-danger'])
          - else
            = form_tag session_path(:user), class: ['navbar-form', 'navbar-right'], role: :form do |f|
              .form-group
                = text_field_tag 'user[email]', "", placeholder: "Email", class: 'form-control'
              .form-group
                = password_field_tag 'user[password]', "", placeholder: "Password", class: 'form-control'
              =button_tag t('layout.sign_in'), class: ['btn', 'btn-primary', 'btn-sm']
              = link_to t('layout.sign_up'), new_user_registration_path, class: ['btn', 'btn-success', 'btn-sm']
    =yield
    = render 'pages/footer'

app/views/layouts/dashboard.html.haml
!!!
%html
  %head
    %title Web extraction engine
    = stylesheet_link_tag    "application", "dashboard", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = yield :head
    = csrf_meta_tags
  %body
    .navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container-fluid
        .navbar-header
          =link_to "Web extraction engine", root_path, class: 'navbar-brand'
        .navbar-collapse.collapse
          %ul.nav.navbar-nav.navbar-left
            %li
              =link_to "#{current_user.nickname || current_user.email}", "#"
          .navbar-right.navbar-form= link_to(t('layout.logout'), destroy_user_session_path, :method => :delete, class: ['btn', 'btn-danger'])
          %ul.nav.navbar-nav.navbar-right
            %li.dropdown
              %a.dropdown-toggle{href: "#", 'data-toggle' => "dropdown"}
                Language
                %b.caret
              %ul.dropdown-menu
                %li
                  =link_to "English", locale: :en
                %li
                  =link_to "日本語", locale: :ja
                %li
                  =link_to "Français", locale: :fr
            %li
              =link_to t('layout.dashboard'), new_website_path
            %li
              =link_to t('layout.help'), documentation_path
    .container-fluid
      .row
        .col-sm-3.col-md-2.sidebar
          %ul.nav.nav-sidebar
            %li
              = link_to t('layout.extraction.new'), new_website_path
            %li
              = link_to t('layout.website.index'), websites_path
            %li
              =link_to t('layout.documentation'), documentation_path

        .col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2.main
          = yield
    .custom_footer= render 'pages/footer'

app/views/layouts/devise.html.haml
!!!
%html
  %head>
    %title Web extraction engine
    = stylesheet_link_tag "application", "devise", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = yield :head
    =stylesheet_link_tag "sign_in", "zocial", "http://fonts.googleapis.com/css?family=Pompiere"
    %meta{name:'google-signin-scope', content: 'profile'}
    %meta{name: "google-signin-clientid", content:"1085235126808.apps.googleusercontent.com"}
    %meta{name: "google-signin-cookiepolicy", content: "single_host_origin"}
    = csrf_meta_tags
  %body
    - if flash[:notice]||flash[:alert]
      .notice=flash[:notice]||flash[:alert]
    =yield
    = render 'pages/footer'